### PR TITLE
Address PyYAML vulnerability

### PR DESCRIPTION
**Pull request by portante**
See https://github.com/performancecopilot/ansible-pcp/security/dependabot/ansible_pytest_extra_requirements.txt/PyYAML/open.

### CODE REVIEW

**Comment by natoscott** [comment]
Hmm, I recall this issue (and associated fix) being considered incompatible with something else, but for the life of me I cannot recall details now.  I notice the linux-system-roles projects have dismissed this alert though.

@richm @nhosoi do you remember all the details of this ... ?  Thanks!
https://github.com/linux-system-roles/metrics/security/dependabot/ansible_pytest_extra_requirements.txt/PyYAML/closed

**Comment by richm** [comment]
> Hmm, I recall this issue (and associated fix) being considered incompatible with something else, but for the life of me I cannot recall details now. I notice the linux-system-roles projects have dismissed this alert though.
> 
> @richm @nhosoi do you remember all the details of this ... ? Thanks! https://github.com/linux-system-roles/metrics/security/dependabot/ansible_pytest_extra_requirements.txt/PyYAML/closed

Do you support EL6 or other platforms that use python 2.6?  If not, then you can get rid of the line with `python_version < "2.7"` - otherwise - we dismissed errors like this in system roles because that code was only used in unit testing for python modules.

**Comment by portante** [comment]
Why not just merge the commit as is and move on?  Is there some harm to it?

**Comment by richm** [comment]
> Why not just merge the commit as is and move on? Is there some harm to it?

No, then you can follow up with removing the line or removing the file entirely if it is not needed i.e. if you just copied/pasted this from system roles, and you don't need to do unit testing, then you can just remove the file (and remove the reference to it in pytest_extra_requirements.txt) with a subsequent PR.

**Comment by natoscott** [comment]
> Do you support EL6 or other platforms that use python 2.6? If

We do support EL6 in these roles.  However, the roles have no python code at all - I suspect we can remove this line entirely (it was indeed cargo culted from the system roles template repo, from memory).  Let me try that... hmm, and probably we don't need the 'idna' line above it either right?  (idna -> https://pypi.org/project/idna/ I guess)

**Comment by richm** [comment]
> > Do you support EL6 or other platforms that use python 2.6? If
> 
> We do support EL6 in these roles. However, the roles have no python code at all - I suspect we can remove this line entirely (it was indeed cargo culted from the system roles template repo, from memory). Let me try that... hmm, and probably we don't need the 'idna' line above it either right? (idna -> https://pypi.org/project/idna/ I guess)

You don't need any of the `*_extra_requirements.txt` files then.  You can just make them 0 length files.

**Pull request merged**
